services:
  plunie_web:
    build:
      context: ../..
      dockerfile: back/docker/Dockerfile
    container_name: plunie_web
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ../../:/var/www
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    env_file:
      - .env
    depends_on:
      - pluniedb
      - mailpit
    networks:
      - plunie_network
    

  # Base de données MariaDB
  pluniedb:
    image: mariadb
    container_name: pluniedb
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - plunie_db:/var/lib/mysql
      - ../../database:/docker-entrypoint-initdb.d
    networks:
      - plunie_network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: plunie_phpmyadmin
    restart: unless-stopped
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=pluniedb
      - PMA_PORT=${PMA_PORT}
    depends_on:
      - pluniedb
    networks:
      - plunie_network

  # Mailpit pour les emails
  mailpit:
    image: axllent/mailpit
    container_name: plunie_mail
    restart: unless-stopped
    ports:
      - ${MAILPIT_HTTP_PORT}:8025
      - ${MAILPIT_SMTP_PORT}:1025
    networks:
      - plunie_network

volumes:
  plunie_db:

networks:
  plunie_network:
    driver: bridge